services:
  web:
    environment:
      - APP_MODE=prod
    ports:
      - "80:5000"
    depends_on:
      init-db:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    profiles: [prod]

  db:
    profiles: [prod]

  init-db:
    profiles: [prod]

  redis:
    profiles: [prod]